server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application.name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

online-pc-shop:
  gateway:
    backend-host: localhost:8082