package com.onlinepcshop.core.domain.entity.enums;

public enum Colors {
    RED, BLUE, GREEN, YELLOW, ORANGE, PURPLE, BROWN, BLACK, WHITE,
    BLACK_BROWN, BLACK_GREEN, BLACK_YELLOW, BLACK_ORANGE,
    WHITE_BROWN, WHITE_GREEN, WHITE_YELLOW, WHITE_ORANGE, WHITE_BLACK,
    GOLD, GOLD_BLACK, GOLD_WHITE;
}
